/* Generated by Yosys 0.9 (git sha1 1979e0b) */

module clocked_adder(A, B, clk, sum);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  input [3:0] A;
  input [3:0] B;
  input clk;
  output [4:0] sum;
  sky130_fd_sc_hd__nand2_1 _33_ (
    .A(_17_),
    .B(_13_),
    .Y(_20_)
  );
  sky130_fd_sc_hd__nand2_1 _34_ (
    .A(_16_),
    .B(_12_),
    .Y(_21_)
  );
  sky130_fd_sc_hd__nor2_1 _35_ (
    .A(_17_),
    .B(_13_),
    .Y(_22_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _36_ (
    .A(_20_),
    .SLEEP(_22_),
    .X(_23_)
  );
  sky130_fd_sc_hd__o21ai_0 _37_ (
    .A1(_21_),
    .A2(_22_),
    .B1(_20_),
    .Y(_24_)
  );
  sky130_fd_sc_hd__xnor2_1 _38_ (
    .A(_18_),
    .B(_14_),
    .Y(_25_)
  );
  sky130_fd_sc_hd__maj3_1 _39_ (
    .A(_18_),
    .B(_14_),
    .C(_24_),
    .X(_26_)
  );
  sky130_fd_sc_hd__maj3_1 _40_ (
    .A(_19_),
    .B(_15_),
    .C(_26_),
    .X(_32_)
  );
  sky130_fd_sc_hd__xnor2_1 _41_ (
    .A(_21_),
    .B(_23_),
    .Y(_29_)
  );
  sky130_fd_sc_hd__xnor2_1 _42_ (
    .A(_24_),
    .B(_25_),
    .Y(_30_)
  );
  sky130_fd_sc_hd__xnor2_1 _43_ (
    .A(_19_),
    .B(_15_),
    .Y(_27_)
  );
  sky130_fd_sc_hd__xnor2_1 _44_ (
    .A(_26_),
    .B(_27_),
    .Y(_31_)
  );
  sky130_fd_sc_hd__xor2_1 _45_ (
    .A(_16_),
    .B(_12_),
    .X(_28_)
  );
  assign _19_ = B[3];
  assign _15_ = A[3];
  assign _18_ = B[2];
  assign _14_ = A[2];
  assign _17_ = B[1];
  assign _13_ = A[1];
  assign _16_ = B[0];
  assign _12_ = A[0];
  assign sum[4] = _32_;
  assign sum[1] = _29_;
  assign sum[2] = _30_;
  assign sum[3] = _31_;
  assign sum[0] = _28_;
endmodule
