/* Generated by Yosys 0.9 (git sha1 1979e0b) */

module clocked_adder(A, B, clk, sum);
  wire [4:0] _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  input [3:0] A;
  input [3:0] B;
  input clk;
  output [4:0] sum;
  wire [4:0] temp;
  sky130_fd_sc_hd__nand2_1 _34_ (
    .A(_23_),
    .B(_19_),
    .Y(_26_)
  );
  sky130_fd_sc_hd__nand2_1 _35_ (
    .A(_22_),
    .B(_18_),
    .Y(_27_)
  );
  sky130_fd_sc_hd__nor2_1 _36_ (
    .A(_23_),
    .B(_19_),
    .Y(_28_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _37_ (
    .A(_26_),
    .SLEEP(_28_),
    .X(_29_)
  );
  sky130_fd_sc_hd__o21ai_0 _38_ (
    .A1(_27_),
    .A2(_28_),
    .B1(_26_),
    .Y(_30_)
  );
  sky130_fd_sc_hd__xnor2_1 _39_ (
    .A(_24_),
    .B(_20_),
    .Y(_31_)
  );
  sky130_fd_sc_hd__maj3_1 _40_ (
    .A(_24_),
    .B(_20_),
    .C(_30_),
    .X(_32_)
  );
  sky130_fd_sc_hd__maj3_1 _41_ (
    .A(_25_),
    .B(_21_),
    .C(_32_),
    .X(_17_)
  );
  sky130_fd_sc_hd__xnor2_1 _42_ (
    .A(_27_),
    .B(_29_),
    .Y(_14_)
  );
  sky130_fd_sc_hd__xnor2_1 _43_ (
    .A(_30_),
    .B(_31_),
    .Y(_15_)
  );
  sky130_fd_sc_hd__xnor2_1 _44_ (
    .A(_25_),
    .B(_21_),
    .Y(_33_)
  );
  sky130_fd_sc_hd__xnor2_1 _45_ (
    .A(_32_),
    .B(_33_),
    .Y(_16_)
  );
  sky130_fd_sc_hd__xor2_1 _46_ (
    .A(_22_),
    .B(_18_),
    .X(_13_)
  );
  sky130_fd_sc_hd__dfxtp_1 _47_ (
    .CLK(clk),
    .D(_00_[0]),
    .Q(temp[0])
  );
  sky130_fd_sc_hd__dfxtp_1 _48_ (
    .CLK(clk),
    .D(_00_[1]),
    .Q(temp[1])
  );
  sky130_fd_sc_hd__dfxtp_1 _49_ (
    .CLK(clk),
    .D(_00_[2]),
    .Q(temp[2])
  );
  sky130_fd_sc_hd__dfxtp_1 _50_ (
    .CLK(clk),
    .D(_00_[3]),
    .Q(temp[3])
  );
  sky130_fd_sc_hd__dfxtp_1 _51_ (
    .CLK(clk),
    .D(_00_[4]),
    .Q(temp[4])
  );
  assign sum = temp;
  assign _24_ = B[2];
  assign _20_ = A[2];
  assign _25_ = B[3];
  assign _21_ = A[3];
  assign _23_ = B[1];
  assign _19_ = A[1];
  assign _22_ = B[0];
  assign _18_ = A[0];
  assign _00_[4] = _17_;
  assign _00_[1] = _14_;
  assign _00_[2] = _15_;
  assign _00_[3] = _16_;
  assign _00_[0] = _13_;
endmodule
